### ISSUE TITLE
Error Response

### ISSUE THREAD

**Issue by akim** [GradientSurfer/Draw2Img#1] opened 2024-01-05 18:42 UTC
Getting the following when running the localserver.

Error response
Error code: 404

Message: File not found.

Error code explanation: HTTPStatus.NOT_FOUND - Nothing matches the given URI.

**Comment by GradientSurfer** [comment] 2024-01-05 18:55
Hi @akim thanks for the report, could you please share some additional details including your OS, the command you ran and the output you saw?  I also want to confirm that you are running `python draw2img/main.py` from the *root directory* of the repo.

**Comment by akim** [comment] 2024-01-05 18:58
Yes - it's on MacOS with Python 3.10.9

Here's the output: 

 % python draw2img/main.py
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  2.98it/s]
INFO:websocket_server:listening: ws://localhost:8079
INFO:draw2img:Web UI URL: http://localhost:8080
127.0.0.1 - - [05/Jan/2024 10:57:13] code 404, message File not found
127.0.0.1 - - [05/Jan/2024 10:57:13] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [05/Jan/2024 10:57:13] code 404, message File not found
127.0.0.1 - - [05/Jan/2024 10:57:13] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [05/Jan/2024 10:57:14] code 404, message File not found
127.0.0.1 - - [05/Jan/2024 10:57:14] "GET / HTTP/1.1" 404 -

**Comment by GradientSurfer** [comment] 2024-01-05 19:07
Thanks for the details, it seems like [this path](https://github.com/GradientSurfer/Draw2Img/blob/84f7b516b0506eee3fb364fb976647e3dd15068a/draw2img/main.py#L18) may not be resolving correctly in your environment for some reason. 

I'm unable to reproduce on my Linux box so far - are you able to investigate with a `print` statement or debugger?

**Comment by nicholas-gh** [comment] 2024-01-05 20:06
The 'Start server' in the README at the moment (84f7b516b0506eee3fb364fb976647e3dd15068a) doesn't mention having to run `npm run build` to populate the `dist/` folder - but that does seem to be required as the `dist` isn't in git

**Comment by GradientSurfer** [comment] 2024-01-05 20:23
Ah yup exactly, sorry for the hassle! I checked in the dist directory now so it won't be necessary to perform the build. This issue should be resolved now @akim, thanks again for reporting.

**Closed as completed** 2024-01-05 20:35 UTC

**Comment by akim** [comment] 2024-01-05 20:50
That was it - thanks!
